# Generated by Django 5.2.1 on 2025-05-12 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipInformation',
            fields=[
                ('ship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ship_name', models.CharField(max_length=255)),
                ('ship_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ship Information',
                'verbose_name_plural': 'Ship Information',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='PortInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_port', models.CharField(max_length=255)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='Navy_registrar.shipinformation')),
            ],
            options={
                'verbose_name': 'Port Information',
                'verbose_name_plural': 'Port Information',
            },
        ),
        migrations.CreateModel(
            name='MissionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(max_length=255)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='Navy_registrar.shipinformation')),
            ],
            options={
                'verbose_name': 'Mission Information',
                'verbose_name_plural': 'Mission Information',
            },
        ),
        migrations.CreateModel(
            name='CrewInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_size', models.IntegerField()),
                ('commander_name', models.CharField(max_length=255)),
                ('commander_rank', models.CharField(max_length=255)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='Navy_registrar.shipinformation')),
            ],
            options={
                'verbose_name': 'Crew Information',
                'verbose_name_plural': 'Crew Information',
            },
        ),
    ]
